export const DUMMY_DATA = [
  {
    curpMessageError: 'mi mensaje personalizado CURP',
    dateMessageError: 'mi mensaje personalizado DATE',
    emailMessageError: 'mi mensaje personalizado EMAIL',
    id: 'UNO',
    numberMessageError: 'mi mensaje personalizado NUMBER',
    requiredMessageError: 'mi mensaje personalizado REQUIRED',
    rfcMessageError: 'mi mensaje personalizado RFC',
    rfckeyCodeMessageError: 'mi mensaje personalizado RFC CLAVE',
    texNumMessageError: 'mi mensaje personalizado TEXT y NUMERO',
    textMessageError: 'mi mensaje personalizado TEXT',
    title: 'TITULO UNO',
    type: ['R', 'RFC_KEY_CODE'],
    value: 'XXXX920804LP7',
  },
  {
    curpMessageError: 'mi mensaje personalizado CURP',
    dateMessageError: 'mi mensaje personalizado DATE',
    emailMessageError: 'mi mensaje personalizado EMAIL',
    id: 'DOS',
    numberMessageError: 'mi mensaje personalizado NUMBER',
    requiredMessageError: 'mi mensaje personalizado REQUIRED',
    rfcMessageError: 'mi mensaje personalizado RFC',
    rfckeyCodeMessageError: 'mi mensaje personalizado RFC CLAVE',
    texNumMessageError: 'mi mensaje personalizado TEXT y NUMERO',
    textMessageError: 'mi mensaje personalizado TEXT',
    title: 'TITULO UNO',
    type: ['T'],
    value: 'texto',
  },
  {
    curpMessageError: 'mi mensaje personalizado CURP',
    dateMessageError: 'mi mensaje personalizado DATE',
    emailMessageError: 'mi mensaje personalizado EMAIL',
    id: 'TRES',
    numberMessageError: 'mi mensaje personalizado NUMBER',
    requiredMessageError: 'mi mensaje personalizado REQUIRED',
    rfcMessageError: 'mi mensaje personalizado RFC',
    rfckeyCodeMessageError: 'mi mensaje personalizado RFC CLAVE',
    texNumMessageError: 'mi mensaje personalizado TEXT y NUMERO',
    textMessageError: 'mi mensaje personalizado TEXT',
    title: 'TITULO TRES',
    type: 'N',
    value: 23423,
  },
];
